### ISSUE TITLE
ejected when eat

### ISSUE THREAD

**Issue by Nartsu55** [josephworks/AtomMC#133]
Hello I have a problème on my server, I have test all item who can eat and juste the cake don't eject me
log : https://mclo.gs/6zj94nh

**Comment by josephworks** [comment]
Please post the full log, list of plugins, and list of mods. Also, please clarify your issue. I am not sure what you mean.

**Comment by Nartsu55** [comment]
https://mclo.gs/u3SG7LF

I tested with and without plugins, and it kicks us when we eat any vanilla food

**Comment by Nartsu55** [comment]
iron chest and custom npc, the other mods don't charged at start because it's client mods

**Comment by josephworks** [comment]
Also, are you using the latest libraries and atom?

**Comment by Nartsu55** [comment]
yes, i have redownload libs and server jar one week ago

**Comment by josephworks** [comment]
Are you using anything like protocol lib or anything that modifies packets?

**Comment by Nartsu55** [comment]
i have normaly protocol lib for my playerdata sync plugins

**Comment by josephworks** [comment]
Something is messing with the packets when you eat. Does the server experience lag when you eat?

**Comment by Nartsu55** [comment]
no lag and no tps lost

**Comment by Nartsu55** [comment]
it affects the player who eats

**Comment by Nartsu55** [comment]
I have re test with an clean install and the latest release and i been kicked with the same warning
and an other information today is whitout waterfall proxy and 2 day ago with waterfall proxy

**Comment by josephworks** [comment]
You will have to resend the logs. you should have mentioned that you were using waterfall..

**Comment by Nartsu55** [comment]
the logs is identical of precedent log

**Comment by Nartsu55** [comment]
i don't have a lot of memory in my ssd and i have delete the dir of test server but the warning when we kick is identical
and the proxy not change the result

**Comment by josephworks** [comment]
Please share the current log then

**Comment by Nartsu55** [comment]
of what ? on serveur of test with the latest version of your jenkinks?

**Comment by Nartsu55** [comment]
or on of my server link by waterfall

**Comment by josephworks** [comment]
both

**Comment by Nartsu55** [comment]
i send log tomorow, i don't have the time now

**Comment by josephworks** [comment]
ok, I guess that's fine, but I may not answer tomorrow.

**Comment by Nartsu55** [comment]
it not a probleme

**Comment by josephworks** [comment]
duplicate of #132
