### ISSUE TITLE
Pixelmon 1.12.2 WorldProvider NPE Crash

### ISSUE THREAD

**Issue by ThunderModder** [josephworks/AtomMC#56]
Im trying to run 257 build with Pixelmon-1.12.2-7.0.6-universal, and im getting NPE there. It seems like World object is null there. But on vanilla minecraft it works well.

![crash](https://user-images.githubusercontent.com/35922210/61737924-de1fcd00-ad91-11e9-8b51-02e1dd746da7.png)

**Comment by josephworks** [comment]
ok, I think that this is an NMS error. I am not certain when this will be
fixed.

**Comment by josephworks** [comment]
@ThunderModder I think this has been fixed. Please update Atom and dry again.
