### ISSUE TITLE
Crash client when eat food

### ISSUE THREAD

**Issue by KoteMyrok** [josephworks/AtomMC#68]
14.08 19:55:27 [Server] Server thread/WARN Failed to handle packet for /176.59.193.201:24914
14.08 19:55:27 [Server] INFO net.minecraft.util.ReportedException: Ticking player
14.08 19:55:27 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:507) ~[oq.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:245) ~[pa.class:?]
14.08 19:55:27 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:194) ~[NetworkDispatcher$1.class:HEAD-d8ce741]
14.08 19:55:27 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:233) ~[gw.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:149) [oz.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:786) [MinecraftServer.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:394) [nz.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:635) [MinecraftServer.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528) [MinecraftServer.class:?]
14.08 19:55:27 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
14.08 19:55:27 [Server] INFO Caused by: java.lang.NullPointerException
14.08 19:55:27 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callFoodLevelChangeEvent(CraftEventFactory.java:707) ~[CraftEventFactory.class:HEAD-d8ce741]
14.08 19:55:27 [Server] INFO at net.minecraft.util.FoodStats.func_151686_a(FoodStats.java:40) ~[afp.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.item.ItemFood.func_77654_b(ItemFood.java:41) ~[aij.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:246) ~[aip.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_71036_o(EntityLivingBase.java:2575) ~[vp.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:1188) ~[oq.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2482) ~[vp.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1992) ~[vp.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:230) ~[aed.class:?]
14.08 19:55:27 [Server] INFO at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:428) ~[oq.class:?]
14.08 19:55:27 [Server] INFO ... 9 more
14.08 19:55:27 [Disconnect] User MrKoteMyrok has disconnected, reason: Internal server error
14.08 19:55:27 [Server] Server thread/INFO MrKoteMyrok вышел из игры

Forge version is same on the server and client

**Comment by KoteMyrok** [comment]
Crash happens without any mods or plugins

**Comment by josephworks** [comment]
This is going to be hard to fix. I will tell you when there is a solution.

**Comment by josephworks** [comment]
Hello,
I believe your issue has finally been fixed in the latest version.
Please download from http://192.168.0.11:8080/job/AtomMC/job/master/lastSuccessfulBuild/artifact/build/libs/
be sure to replace your server's /library folder with the newest libraries.zip
