### ISSUE TITLE
Cannot enchant items

### ISSUE THREAD

**Issue by KoteMyrok** [josephworks/AtomMC#69]
14.08 23:04:36 [Server] INFO java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot add null enchantment
14.08 23:04:36 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_45]
14.08 23:04:36 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_45]
14.08 23:04:36 [Server] INFO at net.minecraft.util.Util.func_181617_a(Util.java:37) [h.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:692) [MinecraftServer.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:394) [nz.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:635) [MinecraftServer.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:528) [MinecraftServer.class:?]
14.08 23:04:36 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]
14.08 23:04:36 [Server] INFO Caused by: java.lang.NullPointerException: Cannot add null enchantment
14.08 23:04:36 [Server] INFO at org.apache.commons.lang3.Validate.notNull(Validate.java:225) ~[commons-lang3-3.5.jar:3.5]
14.08 23:04:36 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftItemStack.addUnsafeEnchantment(CraftItemStack.java:184) ~[CraftItemStack.class:HEAD-d8ce741]
14.08 23:04:36 [Server] INFO at net.minecraft.inventory.ContainerEnchantment.func_75140_a(ContainerEnchantment.java:302) ~[agb.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147338_a(NetHandlerPlayServer.java:2033) ~[pa.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.network.play.client.CPacketEnchantItem.func_148833_a(CPacketEnchantItem.java:25) ~[le.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.network.play.client.CPacketEnchantItem.func_148833_a(CPacketEnchantItem.java:11) ~[le.class:?]
14.08 23:04:36 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:10) ~[hv$1.class:?]
14.08 23:04:36 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_45]
14.08 23:04:36 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_45]
14.08 23:04:36 [Server] INFO at net.minecraft.util.Util.func_181617_a(Util.java:36) ~[h.class:?]
14.08 23:04:36 [Server] INFO ... 5 more

**Comment by josephworks** [comment]
That is weird. It sounds like the enchantments are lost during data
transfer. This might be fixed when we make Minecraft code external because
it would be up to date.

**Comment by josephworks** [comment]
Hello,
I believe your issue has finally been fixed in the latest version.
Please download from http://192.168.0.11:8080/job/AtomMC/job/master/lastSuccessfulBuild/artifact/build/libs/
be sure to replace your server's /library folder with the newest libraries.zip
