### ISSUE TITLE
Server can not start with Quark Mod (Custom ModPack)

### ISSUE THREAD

**Issue by fantahund** [josephworks/AtomMC#75]
[latest.log](https://github.com/josephworks/AtomMC/files/3634506/latest.log)

**Comment by josephworks** [comment]
The quark mod breaks all hybrid server software

**Comment by fantahund** [comment]
No with "CatServer" Does it work O.o

**Comment by josephworks** [comment]
wdym?

**Comment by josephworks** [comment]
It should also break catserver, I might look into that.
